{% set name = "automesh" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32e22cdf4c297edd4d4072dc2fca3e78acd951ea1a97dd0b0662cb9da0d7a718

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
  host:
    - maturin
    - pip
    - python
  run:
    - numpy
    - python

test:
  commands:
    - pip check
  imports:
    - automesh
  requires:
    - pip

about:
  home: https://autotwin.github.io/automesh
  description: Automatic mesh generation.
  dev_url: https://github.com/autotwin/automesh
  license: GPL-2.0-or-later
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: Automatic mesh generation.

extra:
  recipe-maintainers:
    - mrbuche
    - hovey
